# Day 4: Scratchcards

https://adventofcode.com/2023/day/4

I'm helping an elf figure out the value of his scratchcards. In return, he promises to loan me his boat, so I can go see the gardener for further help with my quest.

## Part 1

In this table, numbers on the left are the winning numbers and numbers on the right are the numbers we have. The first match is worth one point and each subsequent match doubles the value of the scratchcard. The 5 cards in the example are worth 8, 2, 2, 1, 0, 0 points, respectively, for a total of 13 points.

In [1]:
sample_input = '''Card 1: 41 48 83 86 17 | 83 86  6 31 17  9 48 53
Card 2: 13 32 20 16 61 | 61 30 68 82 17 32 24 19
Card 3:  1 21 53 59 44 | 69 82 63 72 16 21 14  1
Card 4: 41 92 73 84 69 | 59 84 76 51 58  5 54 83
Card 5: 87 83 26 28 32 | 88 30 70 12 93 22 82 36
Card 6: 31 18 13 56 72 | 74 77 10 23 35 67 36 11'''

In [2]:
def cardvalue(card):
    winning = card[card.find(':')+1 : card.find('|')].split()
    have = card[card.find('|')+1:].split()
    value = 0
    for n in have:
        if n in winning:
            if value == 0:
                value = 1
            else:
                value = value * 2
    return value


cardvalue(sample_input.split('\n')[0])

8

In [3]:
def solve_part1(bigstring):
    cards = bigstring.split('\n')
    sum = 0
    for card in cards:
        sum = sum + cardvalue(card)
    return sum

In [4]:
solve_part1(sample_input)

13

In [5]:
with open('data/day04_in.txt', 'r') as f:
    puzzle_input = f.read()

In [6]:
solve_part1(puzzle_input)

27845

## Part 2

Uh oh, we didn't read the rules. There's no such thing as points. You win a copy of subsequent cards for each match. If card 10 has 5 matching numbers, you win one copy each of cards 11, 12, 13, 14, and 15. Each copy of those cards is processed the same way. The game is structured so you will not win copies of cards beyond the end of the table.

In [7]:
import numpy as np

In [8]:
def cardmatches(card):
    '''returns the number of matching numbers on the card'''
    winning = card[card.find(':')+1 : card.find('|')].split()
    have = card[card.find('|')+1:].split()
    matches = 0
    for n in have:
        if n in winning:
            matches = matches + 1
    return matches

cardmatches(sample_input.split('\n')[0])

4

In [12]:
def calculate_winnings(cards, verbose=False):
    copies = np.ones(len(cards)).astype(int)
    card_index = 0
    while card_index < len(cards):
        if verbose: print(cards[card_index])
        if verbose: print(f'{cardmatches(cards[card_index])} matches')
        copy_index = cardmatches(cards[card_index])
        while copy_index > 0:
            copies[card_index + copy_index] += copies[card_index]
            copy_index = copy_index - 1
        if verbose: print(copies, '\n')
        card_index = card_index + 1
    
    return sum(copies)

calculate_winnings(sample_input.split('\n'), verbose=True)

Card 1: 41 48 83 86 17 | 83 86  6 31 17  9 48 53
4 matches
[1 2 2 2 2 1] 

Card 2: 13 32 20 16 61 | 61 30 68 82 17 32 24 19
2 matches
[1 2 4 4 2 1] 

Card 3:  1 21 53 59 44 | 69 82 63 72 16 21 14  1
2 matches
[1 2 4 8 6 1] 

Card 4: 41 92 73 84 69 | 59 84 76 51 58  5 54 83
1 matches
[ 1  2  4  8 14  1] 

Card 5: 87 83 26 28 32 | 88 30 70 12 93 22 82 36
0 matches
[ 1  2  4  8 14  1] 

Card 6: 31 18 13 56 72 | 74 77 10 23 35 67 36 11
0 matches
[ 1  2  4  8 14  1] 



30

In [13]:
calculate_winnings(puzzle_input.split('\n'), verbose=False)

9496801

9496801 is correct.